PROGRAM = salsa

SRC = main.c $(wildcard src/*.c) lib/parson/parson.c
OBJS = $(patsubst %.c, %.o, $(SRC) )

CC = gcc
CFLAGS = -Wall -O2 -lwiringPi

BINPATH = /usr/local/bin

.SUFFIXES: .c .o

.PHONY: all
all: $(PROGRAM)

$(PROGRAM): $(OBJS)
	$(depend)
	$(CC) -o $(PROGRAM) $^

.c.o:
	$(CC) $(CFLAGS) -c $<

.PHONY: clean
clean:
	$(RM) $(PROGRAM) $(OBJS) *.o

.PHONY: depend
depend:
	makedepend -- $(CFLAGS) -- $(OBJS)

.PHONY: install
install:
	mv $(PROGRAM) $(BINPATH)
# DO NOT DELETE
